= `nixlab`
My homelab/network configuration, primarily using NixOS flakes for deployment.

== Network Anatomy
* Using tailscale as a meshnet VPN to connect all of my machines together, as well as funneling some services to the public internet

=== Services
* WIP `squeeze`: Runs basically all of my self hosted services
** Runs as a VM on my proxmox instance on my Dell Poweredge T420
** Should start automatically when proxmox boots up
** Hosts my file share, which is served either through nextcloud or sshfs
** Runs most of my self-hosted services, asdf

=== Automation
* TODO ``: Dedicated n8n automation server
** Running on an always free Oracle VPS
*** Could potentially offload AI agents to a VM on my T420, but this should be enough for running at least 1 at a time (I think)
* TODO ``: Dedicated wake-on-Lan server
** Running on a Raspberry Pi 3
** Used to turn on my T420

=== Clients
* My phones and laptops
* Should just be running tailscale, syncthing, and either sshfs or nextcloud to access my file share

== Wishlist
* Either NVIDIA teslas and a new PSU for my T420 or a seperate machine dedicated for AI agents
* Maybe a NAS that I can migrate my services to and have the T420 act as a Promox backup server
* A Raspberry Pi 5 or similar to run automation when `` is down
** Could just be something that can run really small AI agents and uses very little power
** Currently using a Raspberry Pi 3, which leaves a lot to be desired
* A new gaming setup so that I can use my gaming laptop for ai
